### ISSUE TITLE
Expand template_provenance() to handle generating provenance for external packages

### ISSUE THREAD

**Issue by kzollove** [EDIorg/EMLassemblyline#100]
template_provenance currently only supports EDI data packages. It seems that the template provides enough information fields to essentially manually create provenance for any dataset. 

systemID field could be specified only for supported repositories (i.e. EDI, maybe NEON in the future).

**Comment by clnsmth** [comment]
This would be a great addition @kzollove.

**Comment by clnsmth** [comment]
Hmmm ... @kzollove please verify that this feature is not yet implemented. See https://github.com/EDIorg/EMLassemblyline/blob/3f9bcbcbf850de1ce66031ece8fd6018b12d8d0e/R/make_eml.R#L999

**Comment by kzollove** [comment]
Thanks for pointing this out @clnsmth. I should've done a deeper dive before making this issue. I will close this out.

I have some very minor enhancements I will address in a different issue
