### ISSUE TITLE
Error: Failed to install 'EMLassemblyline' from GitHub

### ISSUE THREAD

**Issue by Cal10Lee** [EDIorg/EMLassemblyline#113]
I attempted to install the EML package from r-studio (using this line of code: remotes::install_github("EDIorg/EMLassemblyline") and got this error message:

Error: Failed to install 'EMLassemblyline' from GitHub:
  Failed to install 'taxonomyCleanr' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`EDIorg`) and repo name (`EDIutils`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

I'm still a relatively new r user, is there something I'm missing? Thank you in advance.

**Comment by yvanlebras** [comment]
Hi @Cal10Lee 

I just try on my RStudio instance to install it with this command `remotes::install_github("EDIorg/EMLassemblyline")` (the same than you) and it seems to work. Are you sure this is not "just" a transient internet connexion issue ?

**Comment by clnsmth** [comment]
Thanks for helping with this @yvanlebras. Yes, the 404 response suggests the client was unable to communicate with the GitHub server.

@Cal10Lee if this is still an issue, would you mind sending the response you get from running `sessionInfo()` in your RStudio  Console? Thanks.

**Comment by clnsmth** [comment]
Hi @Cal10Lee. The bug has been resolved and the fix pushed to the master branch. Please try reinstalling again (`remotes::install_github("EDIorg/EMLassemblyline")`) and let me know if you have any issues. Thanks for your patience.

**Comment by Cal10Lee** [comment]
Just installed it, no issues. Thank you!

**Comment by clnsmth** [comment]
Thank you for uncovering this bug @Cal10Lee!
