### ISSUE TITLE
template_geographic_coverage requires a character vector for site.col  

### ISSUE THREAD

**Issue by RobLBaker** [EDIorg/EMLassemblyline#121]
Currently if the site names in site.col are integers (1, 2, 3, 4, ... N) the following error occurs:

Templating geographic coverage ...
geographic_coverage.txt
Error in enc2utf8(site_out) : argument is not a character vector

Is it possible to either allow template_georaphic_coverage to work with integers or give the function an option to force R to read the site column as characters rather than defaulting to integers?

**Comment by clnsmth** [comment]
Thanks for reporting this bug @RobLBaker. I like your idea of allowing `template_geographic_coverage()` to accept integers (and doubles). This is a simple fix and I should be able to get it out tomorrow.

**Comment by clnsmth** [comment]
@RobLBaker The fix is in branch `121-geocov-sitecol`. Please give it a test when you have a chance and let me know if it works for you. Install this branch with:

`devtools::install_github("EDIorg/EMLassemblyline", ref = "121-geocov-sitecol")`

**Comment by RobLBaker** [comment]
Seems to work great, thanks!

**Comment by clnsmth** [comment]
Thanks again @RobLBaker. This fix has been merged into the master branch.
