### ISSUE TITLE
taxonomicCoverage no longer written to EML

### ISSUE THREAD

**Issue by RobLBaker** [EDIorg/EMLassemblyline#136]
Hello!

I recently noticed that EMLassemblyline is no longer writing the taxonomicCoverage component to .xml when calling "make_eml()".  I have tested this on a couple of different datasets and temporalCoverage is successfully written, but taxonomicCoverage is not, despite the taxonomy_coverage.txt file successfully being generated.

I suspect the issue may trace back to changes made 2 weeks ago in taxonomyCleanr where makeTaxonomicCoverage() was set to internal only. EMLassemblyline's make_eml() function calls taxonomyCleanr::makeTaxonomicCoverage on line 896. 

This may not be the only issue, but it does appear to be one of the issues. I've cross-posted this issue on taxonomyCleanr. Please excuse the extra post.

**Comment by clnsmth** [comment]
Fixed by https://github.com/EDIorg/taxonomyCleanr/commit/c1118bbce83bcbc72eb3c5d5e5c604863fe1e0d0

See also https://github.com/EDIorg/taxonomyCleanr/issues/49
