### ISSUE TITLE
include attributeLabel in EML

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#19]
EML attributes should have a human readable label in addition to the attributeName and definition. best practices p 32

**Comment by clnsmth** [comment]
Thanks for highlighting this best practice @mobb. On one hand I see the value of adding a human readable label, on the other I don't see this adding value that is not already provided by the attributeDefinition. A primary objective of `EMLassemblyline` is to optimize ease of use with EML richness and quality. Adding inputs (required or optional) requires more effort or assessment on the users part.

If we decide an attribute label is superfluous to the general user but valuable to an advanced user, we could exclude it from the `template files` imported to the general users work-space but support it in a profile export from an advanced users metabase or the like?

**Comment by clnsmth** [comment]
This was implemented in b54fff5e4feaa2038b014091e74754ee6a0a0cc7.
