### ISSUE TITLE
entityName should not be the same as the objectName

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#20]
The object name is a filename (required by pasta). but the Entity name does not have to be. In fact, you can think of the entity name as a class ("Time series of temperature at site X") and the objectName as an instantiation of that class ("siteX_temperature_20181231.csv")
example on EML BP p36

**Comment by clnsmth** [comment]
Thanks for this recommendation @mobb . This feature was implemented on 2019-02-28. [Here is the first data package created with this enhancement](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=283&revision=2).
