### ISSUE TITLE
note for documentation, using md5 hash

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#22]
R's md5 command cannot use linux style shortcuts. you have to write out the path, you cannot not say ~/some/path/in/users/home 
maybe everyone else already knows that - but the response is 'file not found'.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @mobb.

What do you mean by "R's md5 command"? Do you mean `EMLassemblyline`s method of calculating MD5 for a data object?

**Comment by clnsmth** [comment]
Non-issue
