### ISSUE TITLE
Entity Name

### ISSUE THREAD

**Issue by cgries** [EDIorg/EMLassemblyline#24]
It appears that the content from data.table.description in make_eml is used to fill in the entity name. However, they are not the same and entity name should be specified separately.

**Comment by clnsmth** [comment]
`data.table.name` and `other.entity.name` have been added as arguments to `make_eml()`. This fix defaults `data.table.name` to `data.table` and `other.entity.name` to `other.entity` with a warning message.

These changes (b54fff5e4feaa2038b014091e74754ee6a0a0cc7) have been merged into the development branch.
