### ISSUE TITLE
taxonomic_coverage(): Allow inputs from more than one table

### ISSUE THREAD

**Issue by clnsmth** [EDIorg/EMLassemblyline#28]
... by accepting multiple inputs to the "taxa.table" and "taxa.col" arguments, example:

```
template_taxonomic_coverage(
  path = '/path/to/template/files',
  data.path = '/path/to/data/files',
  taxa.table = c('data.table.1', 'data.table.2'),
  taxa.col = c('col.dt.1', 'col.dt.2'),
  taxa.name.type = 'scientific',
  taxa.authority = c(3, 4, 12)
)
```

**Comment by clnsmth** [comment]
This enhancement is now available on the development branch.

**Comment by earnaud** [comment]
I am currently trying the last improvement of `template_taxonomic_coverage()` with 4 data tables. It still displays a message "taxonomic_coverage.txt already exists" thus impeding to define taxonomic coverage accross multiple data tables.

**Comment by earnaud** [comment]
Briefly, here is a way to achieve it (I will let you re-write it to adapt to your code writing style): this takes 
```r
files <- paste0(data.path,"/",taxa.table)
taxa.raw <- unique(sapply(files, function(f) {
  if(length(taxa.col) > 1)
    target.col <- taxa.col[f %in% files] # taxa.col vector is expected to be written in the same order as taxa.table
  else
    target.col <- taxa.col
  # taxa.col is expected to be at least of length 1
  fread(f)[[target.col]]
})) # 'sep' argument might be detailed

# output: taxa.raw contains unique taxa names (contained in taxa.col columns)
```
**Constraints**: length(taxa.col) == length(taxa.table) || length(taxa.col) == 1 (specific col name per file OR same col name for all files)
**Possible improvements**: check for the 'sep' argument of `fread()` to be pre-filled.

**Comment by clnsmth** [comment]
Thanks for this information @earnaud. Would you mind posting your call to `template_taxonomic_coverage()` with the 4 table inputs? It will help me diagnose the issue you're encountering. Thanks!

**Comment by earnaud** [comment]
You shall find here a R script (in .txt cause .R is not supported on GitHub). Just change the variables at the beginning, and source it (beware: it starts by erasing anything in your local environment). 
[record.txt](https://github.com/EDIorg/EMLassemblyline/files/3326140/record.txt)
Also, I reinstalled EML AL package through its dev branch, but I might have made a mistake on this move. Let me know if this does not reproduce any error I have described.

**Comment by clnsmth** [comment]
Hi @earnaud, I suspect the issue is occurring because each `taxa.table` is missing a corresponding `taxa.col`, even if the same for all tables (see documentation for the development version of `template_taxonomic_coverage()`). Your call in `record.txt` needs only slight modification:

```
template_taxonomic_coverage(
    path = 'pkg.CES2.eporcher/metadata_templates/',
    data.path = 'pkg.CES2.eporcher/data_objects/',
    taxa.table = c("SupplementaryTable1.csv",
                   "SupplementaryTable2.csv",
                   "SupplementaryTable3.csv",
                   "SupplementaryTable4.csv"),
    taxa.col = c("Sp_name",
                 "Sp_name",
                 "Sp_name",
                 "Sp_name"),
    taxa.authority = c(3,11),
    taxa.name.type = 'both'
)
```
I can verify that this fixes the issue if you link me to the four tables referenced in `record.txt`.

Regarding the error _"taxonomic_coverage.txt already exists!"_, this is a safety measure that keeps a user from overwriting their work with a careless call to `template_taxonomic_coverage()`. The taxonomic_coverage.txt file will have to be removed from `path` in order for the function to run.

**Comment by clnsmth** [comment]
Done (see 28623bc293a2b020bb03a358fe5f6cb303a09b62)
