### ISSUE TITLE
Suggested: a template R-script for assembling EML

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#36]
When I run EMLAssemblyLine, I look for an example to use as a starter-script (from another data package) and edit it. Some example scripts are better than others. I would like a template script that contained all the essential features. An added benefit, is that when new features are added, they could appear right away in the template script.

**Comment by mobb** [comment]
related: #37

**Comment by earnaud** [comment]
One of our colleague worked during one month on producing data packages through EML assembly line (most of the results have been published [here](https://openstack-192-168-100-101.genouest.org/metacatui/data) (here)[https://openstack-192-168-100-101.genouest.org/metacatui/data] ). I think the script related to the writing of those data packages are also in the data package. 
I will ask her to send the script here as soon as possible.

**Comment by clnsmth** [comment]
Here are the data packaging scripts and template files I've created for EDI contributors ([link](https://github.com/EDIorg/DataPackages)).
