### ISSUE TITLE
Validate units

### ISSUE THREAD

**Issue by clnsmth** [EDIorg/EMLassemblyline#38]
Validate units of table attributes and provide meaningful error messages.

**Comment by mobb** [comment]
Note that in EML 2.2, you will want to filter the EML unit dictionary to only the units that are NOT `deprecatedInFavorOf`

**Comment by clnsmth** [comment]
This enhancement (3ca2e97964d2c402cd2dae8f579c39f4f5c05fb7) has been merged into the development branch.
