### ISSUE TITLE
categorical variables are not detected 

### ISSUE THREAD

**Issue by earnaud** [EDIorg/EMLassemblyline#40]
As reported in [this pull request](https://github.com/earnaud/MetaShARK-v2/commit/b51671c97e89158a5d0c13f948b72f6dfc1c9126) from the MetaShARK repository (issue #9 ), the `template_categorical_variables` return the following error:
```r
Templating categorical variables ...
Warning in utils::read.table(file = paste0(path, "/", templates[i]), header = TRUE,  :
  cols = 1 != length(data) = 7
Warning in utils::read.table(file = paste0(path, "/", templates[i]), header = TRUE,  :
  cols = 1 != length(data) = 7
No categorical variables found.
No categorical variables found.
Done.
```
(Note that this is not an internal error in the function). 
In fact, there are actually two problems:
- the dimension of the read table (aka the `attributes_*.txt` files) seem to be mistaken
- the categorical variables are not found

**Comment by earnaud** [comment]
Here are views of the content of the "attributes_*.txt" files built from provided ones:
*nitrogen.txt*
![image](https://user-images.githubusercontent.com/43677175/67869470-c5137e80-fb2d-11e9-8686-27ea66ef6210.png)
*decomp.csv*
![image](https://user-images.githubusercontent.com/43677175/67869504-d2306d80-fb2d-11e9-86cd-0bf03eb077dd.png)

**Comment by clnsmth** [comment]
Thanks for reporting this issue @earnaud. The attributes template looks good, but I suspect the problem is related to the data tables it's referencing. What files do your directories at `path` and `data.path` contain?

**Comment by clnsmth** [comment]
Is this still an issue @earnaud?

**Comment by earnaud** [comment]
The issue is not met anymore.

**Comment by earnaud** [comment]
I do not want to open a new issue as this is linked: 

I get some variables which shall be detected as "character" which are indeed detected as "categorical". I would suggest this metric to guess the actual nature of a variable:

- character if diversity (number of different terms) > modal occurrence (maximum occurrence of one term)
- categorical else

which could be translated in R as: 

```
type <- ifelse( length(unique(var)) > max(table(var)), # alternatively, mean() could be used. Any way, it is just an approximation
  "character", # high diversity
  "categorical" # high repetitions
)
```

**Comment by clnsmth** [comment]
This would be a nice Improvement @earnaud . Would you mind refactoring `template_table_attributes()` ([beginning at line 223](https://github.com/EDIorg/EMLassemblyline/blob/80b5c1914c6ef0c1ebe56f0a2b5bd9d9da77f3d7/R/template_table_attributes.R#L221)) and send as a pull request?

**Comment by earnaud** [comment]
I will do it with the #77 review

**Comment by clnsmth** [comment]
Done
