### ISSUE TITLE
template_categorical_variables - empty catvar tables cause R to quit explosively 

### ISSUE THREAD

**Issue by mobb** [EDIorg/EMLassemblyline#58]
**Background**:
This function looks through ALL the objects in the data_objects dir and creates a partly-populated template for each one that it finds categorial values for (presumably by looking at the declaration in the attributes_*txt file). this seems to work fine.

**Problem**:
However. the default set of catvar tables don't play well with the rest of the code in the case where the operator (me) is not ready to create EML for all the entities. My make_eml code has only two data entities defined out of 15-20 anticipated. All the data objects were place into the data_objects dir, as directed (https://ediorg.github.io/EMLassemblyline/articles/organize_data_package.html)

My experience after running template_categorical_variables: R quit with no explanation, just an image of a bomb. I was lucky, in that creating catvar tables was the only change I had made to my setup, so I suspected the bomb-out was due to a mismatch between the catvar_* tables and either the entities list or the attributes_* tables.

My solution: I moved all the not-yet-used catvar_* tables to a holding area. Now R does not bomb out; catvars were used properly.

**Suggested fix**: 
short term: 
describe this gotcha in the documentation. First, just describe what the template function output is, and what the code-requirements are (that all must be filled out before any are used). This behavior is different than the other attribute_* tables -- it appears that attribute_* can stay in the metadata_templates dir unused. Follow up to advise the user that if they are not going to use all the catvar tables right away, to move the unused ones to a holding space. 

Text belongs on this page: https://ediorg.github.io/EMLassemblyline/reference/template_table_attributes.html

Long term: 
add a param to the `template_categorical_variables()` function to specify which attribute_* tables to create catvars for. Or if you are ready to do them all, then option = ALL. By naming them explicitly, 
- users can make only the ones they need, and go back and create more later. 
- users won't get the bombed-out R scenario. 

An alternative is an optional third path to the functions params, e.g., one for the holding_area if users aren't ready for all catvars right away.

disclaimer:
Building large packages (many entities) may not be a common use case for EAL. If you don't anticipate this happening, disregard this issue. Or if I am msiinterpreting EAL behavior, please advise on what I did wrong.

**Comment by mobb** [comment]
adding a param to spec which attribute_* table will need catvars also helps get around R's tendency to over-categorize table columns. Most of the time, the first thing I have to do is downgrade 'categorical' to 'character' in many attribute_*.txt tables after looking more closely at the data. so being able to recreate a catvar table easily would help.

**Comment by clnsmth** [comment]
Thanks for these suggestions @mobb. 

I'll update the [EMLassemblyline overview page](https://ediorg.github.io/EMLassemblyline/articles/overview.html) to make the order of operations more clear (i.e. templates need to be **COMPLETED** before calling `make_eml()`). Also, I'm actively working on #6 and #35 to improve metadata template validation to provide users better warning + error messaging. 

Allowing a user to create a partial EML document, from partially completed metadata templates, will be implemented in #34.

**Comment by mobb** [comment]
Re partially-completed templates: this seems to already be possible for the attribute* templates; I have several incomplete ones in the metadata_templates dir and EAL ignores them. But it seems to not ignore the incomplete catvar* templates in the same dir.

**Comment by yvanlebras** [comment]
It seems to me this "bug" is now solved isn't it ?
