### ISSUE TITLE
template_categorical_variables(): Drop missing value code from output when defined

### ISSUE THREAD

**Issue by clnsmth** [EDIorg/EMLassemblyline#67]
If a missing value code is specified a table attribute template, then don't ask a user to define it in the corresponding categorical variables template.

**Comment by earnaud** [comment]
I am experiencing a trouble with this: I want to complete the template for categorical variables, but I get : 
```
Data table attributes (BDD_Kakila_v2_20201103PNDB_taxon.csv, Required) - Data table attributes will be dropped from the EML until these issues are fixed:
1.  Undefined units. Units must be from the EML standard unit dictionary or defined as custom units. The units of these attributes are undefined: code_taxon, famille, nom_scientifique, nom_commun, code_espece_omm_gde_cca, code_espece_ema
```
Here is a link for the data file. The attributes table has only one numeric attribute (`code_reference`), which unit is set to "dimensionless" (from `EML::get_unitList()`). 

[BDD_Kakila_v2_20201103PNDB_taxon.zip](https://github.com/EDIorg/EMLassemblyline/files/5560746/BDD_Kakila_v2_20201103PNDB_taxon.zip)

**Comment by clnsmth** [comment]
@earnaud This was a bug in version 2.0.3 of the EML library. Try again with EML 2.0.4 installed.

**Comment by earnaud** [comment]
Bug is still happening with 2.0.4.
