### ISSUE TITLE
ampersand in TextType

### ISSUE THREAD

**Issue by cgries** [EDIorg/EMLassemblyline#70]
& is being converted to &amp;amp; but should be only &amp; in TextType, not in other fields.

**Comment by mobb** [comment]
`&` is the escape character for XML, so the only way to render it anywhere in EML is by converting it to its entity reference (`&amp;`). so this behavior is correct. It will appear as `&` when the EML is processed.

**Comment by cgries** [comment]
sorry, it munged up my report by displaying it correctly on this webpage here in git. The problem is that it adds a 'amp;' at the end of the correct conversion

**Comment by mobb** [comment]
you mean it does this? `&amp;&amp;` (put it in a code block to preserve)

I have found that conversions to TextType are faulty in general.  I think this is the EML-R package, not EAL, though. For some characters, I have gotten around this by escaping them, in the text file, e.g, `\"quoted text\"`  or `O\'Brien`. not sure if that will work for ampersands - might be safest to write them out (the word `and`)

**Comment by cgries** [comment]
not quite, it converts into `&amp;amp;`
