### ISSUE TITLE
Update for R4.0?

### ISSUE THREAD

**Issue by trashbirdecology** [EDIorg/EMLassemblyline#71]
Are there plans to soon update the package to be compatible with 4.0? Asking for a friend...

**Comment by clnsmth** [comment]
Hi @TrashBirdEcology. It should already be working for R 4.0. Are there any particular errors that are coming up?

**Comment by clnsmth** [comment]
This has been fixed and is no longer an issue.

**Comment by trashbirdecology** [comment]
no i was just hesitant to use under assumption it would have bugs
