### ISSUE TITLE
How can issues() content be reset ?

### ISSUE THREAD

**Issue by earnaud** [EDIorg/EMLassemblyline#79]
I am having some troubles with the issues() function. At the start of MetaShARK, it appears to be already filled. 

- How can it be reset? 

- How can I know from which call the listed issues come from?

Thanks by advance.

**Comment by earnaud** [comment]
I guess `template_issues` variable has something to see with it?

**Comment by earnaud** [comment]
Ok, I got it: `template_issues` is located in the .GlobalEnv(). I would recommend using the R `options()` to set an env in which to store `template_issues()`, with .GlobalEnv as a default. This would allow 1/ to avoid residual variables after running a script and 2/ better shiny app access to this issue management facility.

**Comment by clnsmth** [comment]
Good sleuthing Elie! Would you mind putting together a Paul request for
this feature?
