### ISSUE TITLE
Provenance tracking: Add methods for EDI data packages or external sources 

### ISSUE THREAD

**Issue by clnsmth** [EDIorg/EMLassemblyline#8]
Support provenance tracking of data sources located in the Environmental Data Initiative (EDI) repository as well as external sources. Provenance EML can be harvested via the PASTA+ API if the source data package is known. [Required fields of a provenance node can be found in this example](https://portal.edirepository.org/nis/provenanceGenerator?packageid=edi.200.2). Perhaps a template file is the best method for collecting provenance info of an external source?

**Comment by clnsmth** [comment]
One possibility is developing the function `template_provenance()` with the arguments:

`path` (character) Path to the metadata templates directory where the provenance.txt table will be written
`system.id` (character) Identifier of the system(s) in which the data object resides. Default is NULL.
`package.id` (character) Identifier of the data package(s) in the corresponding `system.id`. Default is NULL.

... and behavior:

- If only `path` is supplied, then a blank template is written.
- If a supported `system.id` and `package.id` pairing is supplied, then the function downloads and parses the relevant metadata into the fields described below and writes the template to `path`.

[Example provenance.txt](https://docs.google.com/spreadsheets/d/1UevPFHbzy1mzoHqjXuYs2ZkPHL1UgQVUkIKMYLmaaRQ/edit?usp=sharing)

Fields and definitions:
__systemID__ System in which the data reside
__packageID__ Data package identifier
__title__ Data package/resource title
__givenName__ Given name
__surName__ Sur name
__role__ Role (expected is a creator and contact)
__organizationName__ Organization name
__email__ Email address
__onlineDescription__ Description of the online distribution
__url__ URL of the data resource

**Comment by cgries** [comment]
Based on a specific dataset: The EDI metadata template has a table for documenting provenance that asks for: dataset title, URL or DOI, creator (name and e-mail), contact (name and e-mail). So, looking at the suggested fields I am not sure what would go into systemID or packageID, since the only 'ID' is the URL for most of the outside datasets. Many don't even have an URL/DOI, if they were just provided by the author of a paper. Some of the creators are organizations and none seems to have an e-mail ....

**Comment by clnsmth** [comment]
Thanks for this info @cgries. As you suggest, the  **url** field makes **systemID** and **packageID** redundant, but can be used as function arguments to auto populate this template.
