### ISSUE TITLE
"taxa.authority" contains unsupported authority IDs

### ISSUE THREAD

**Issue by juddpatterson** [EDIorg/EMLassemblyline#82]
We are creating a few EML's this week and just ran into an issue when trying to use ITIS to create the taxonomic_coverage.txt file:

```
> template_taxonomic_coverage(path = veg_folder, data.path = veg_folder, taxa.table = veg_file, taxa.col = veg_taxa_field, taxa.authority = c(3,11), taxa.name.type = 'scientific')
Templating taxonomic coverage ...
Error: Input argument "taxa.authority" contains unsupported authority IDs.
```
If we change to just 11 (GBIF) it works fine, but the overall coverage is not as complete as ITIS. I know this same function worked (on a similar CSV) last week, so I'm wondering if the ITIS web service changed or is not working. Just curious if others are also seeing an issuing resolving taxa with ITIS. Thanks!

**Comment by clnsmth** [comment]
Thanks for reporting this issue @juddpatterson. ITIS appears to be working fine and a quick test suggests a bug in taxonomyCleanr. I'll begin fixing ASAP.

**Comment by clnsmth** [comment]
@juddpatterson the fix is in. Requires taxonomyCleanr 1.5.1. Please let me know if you encounter any issues with the fix, and thanks again for reporting this bug.
