### ISSUE TITLE
Taxonomic coverage not returning authority as expected

### ISSUE THREAD

**Issue by timshep** [EDIorg/EMLassemblyline#89]
I set up the template_taxonomic_coverage to search for species with this setup: "taxa.authority = c(3,9,11)" (ITIS, WORMS, GBIF). When I had a full species name, it was not getting the record from WORMS; it returned the taxon from GBIF. An example is "Dumontia alaskana", which is present in WORMS. The helps has the authority as an ordered vector in decreasing preference.

The output to terminal:
> Searching ITIS for "Dumontia alaskana"
> Searching World Register of Marine Species for "Dumontia alaskana"
> Searching GBIF Backbone Taxonomy for "Dumontia alaskana"
> ==  db: gbif =================
> 
> Retrieving data for taxon 'Dumontia alaskana'

I did get some returns from WORMS but only with a genus only record. Those names might have been unresolved ('doubtful') with the GBIF search like, Polyostea.

**Comment by clnsmth** [comment]
Thanks for reporting this issue @timshep.

Results of my investigation so far: `template_taxonomic_coverage()` passes the inputs to `taxonomyCleanr::resolve_sci_taxa()` which uses `taxize::gnr_resolve()` to see if the specified taxon can be found in the specified data source. For whatever reason, `taxize::gnr_resolve("Dumontia alaskana")` does not list WORMS, even though "Dumontia alaskana" [is in WORMS](marinespecies.org/aphia.php?p=taxdetails&id=158075). Does this hold true for the other taxa you expect to see in WORMS? If not, listing a few of these here would help in my investigation.

Many thanks!

**Comment by timshep** [comment]
Sure,

I wasn't sure about which ones would get returned from WORMS. I was expecting a bit more, but a number seem to have a match in ITIS.

Of the other species that are not in ITIS, 'Blidingia minima var. minima' seems to be the only one that is not a valid name in WORMS. Interesting this entry, 'Polyostea / Polysiphonia sp.', does get a return from WORMS. I'm not sure if the "/" is helping something with the resolve...

I've included the taxon text file that gets output and shows the different species that were in the data set. If need, I can also send the csv file that has the full data.

Tim
​~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tim Shepherd
Data Manager
Southwest Alaska Network
Inventory and Monitoring Program
National Park Service

Anchorage, AK
________________________________
From: Colin Smith ***@***.***>
Sent: Wednesday, September 15, 2021 12:00
To: EDIorg/EMLassemblyline ***@***.***>
Cc: Shepherd, Timothy H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDIorg/EMLassemblyline] Taxonomic coverage not returning authority as expected (#89)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Thanks for reporting this issue @timshep<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimshep&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109590238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B0izL6oKivaCKK%2B2WkitOmCgV97xt0cH7Od25hTulAw%3D&reserved=0>.

Results of my investigation so far: template_taxonomic_coverage() passes the inputs to taxonomyCleanr::resolve_sci_taxa() which uses taxize::gnr_resolve() to see if the specified taxon can be found in the specified data source. For whatever reason, taxize::gnr_resolve("Dumontia alaskana") does not list WORMS, even though "Dumontia alaskana" is in WORMS<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmarinespecies.org%2Faphia.php%3Fp%3Dtaxdetails%26id%3D158075&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109590238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X3Lrw%2FVcCliWAyTTnAONhEySt1ar2yLmSycXSk4WjxA%3D&reserved=0>. Does this hold true for the other taxa you expect to see in WORMS? If not, listing a few of these here would help in my investigation.

Many thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEDIorg%2FEMLassemblyline%2Fissues%2F89%23issuecomment-920334562&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109600190%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UXNbR1K%2FoKL0UeipmbBKXVnVSqw2XRuJ0vqM9AD0Zqw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAED7D3HAMO3OY5PIMJXZ7STUCD3MLANCNFSM5EATA5CQ&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109600190%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HsAjtR9MDZcDBWUbU%2Bo7VK3srmL7Ks%2BbgaVKZh0KoOE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109610145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gl2h5135AbAIsC%2Bflt00O2q%2B%2FOxYbv5dDTu9KFB0GT4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctim_shepherd%40nps.gov%7C8453edc6d1e2497e669a08d9788372b9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637673329109610145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jki5lQ%2B7pUJ5wGqFWjSBtuIAnHu5DYf8qMumKiv%2F9EU%3D&reserved=0>.

name	name_type	name_resolved	authority_system	authority_id
Alaria marginata	scientific	Alaria marginata	ITIS	11293
Anthopleura artemisia	scientific	Anthopleura artemisia	ITIS	52554
barnacle	scientific	NA	NA	NA
Devalaria / Palmaria sp.	scientific	NA	NA	NA
Mytilus trossulus	scientific	Mytilus trossulus	ITIS	567928
Odonthalia / Neorhodomela sp.	scientific	Odonthalia	ITIS	13583
Polyostea / Polysiphonia sp.	scientific	Polyostea	World Register of Marine Species	370081
Soranthera ulvoidea	scientific	Soranthera ulvoidea	ITIS	11066
Ulva / Monostroma sp.	scientific	Ulva	ITIS	6559
bare substrate	scientific	NA	NA	NA
encrusting coralline algae	scientific	NA	NA	NA
Fucus distichus	scientific	Fucus distichus	ITIS	11337
non-coralline algal crust	scientific	NA	NA	NA
Acrosiphonia sp.	scientific	Acrosiphonia	ITIS	6721
Halosaccion glandiforme	scientific	Halosaccion glandiforme	ITIS	12825
Melanosiphon / Scytosiphon sp.	scientific	Melanosiphon	ITIS	11060
Desmarestia aculeata	scientific	Desmarestia aculeata	ITIS	11315
Gloiopeltis furcata	scientific	Gloiopeltis furcata	ITIS	12291
Pylaiella littoralis	scientific	Pylaiella littoralis	ITIS	10777
Phycodrys / Tokidadendron sp.	scientific	Phycodrys	ITIS	13285
Cryptosiphonia woodii	scientific	Cryptosiphonia woodii	ITIS	12254
Boreophyllum / Pyropia / Wildemania sp.	scientific	Boreophyllum	World Register of Marine Species	593555
Endocladia muricata	scientific	Endocladia muricata	ITIS	12287
Urticina crassicornis	scientific	Urticina crassicornis	ITIS	52571
Mastocarpus sp.	scientific	Mastocarpus	World Register of Marine Species	144163
spirorbidae	scientific	Spirorbidae	ITIS	68383
Mazzaella sp.	scientific	Mazzaella	World Register of Marine Species	369878
Cladophora / Chaetomorpha sp.	scientific	Cladophora	ITIS	6763
unidentified brown algae	scientific	NA	NA	NA
Blidingia minima var. minima	scientific	Blidingia minima minima	GBIF Backbone Taxonomy	7229513
encrusitng bryozoan	scientific	NA	NA	NA
Metridium senile	scientific	Metridium senile	ITIS	52737
Analipus japonicus	scientific	Analipus japonicus	ITIS	11002
Leathesia marina	scientific	Leathesia marina	GBIF Backbone Taxonomy	7627628
Elachista sp.	scientific	Elachista	ITIS	10937
Ptilota sp.	scientific	Ptilota	ITIS	13108
Nemalion elminthoides	scientific	Nemalion elminthoides	GBIF Backbone Taxonomy	NA
Callithamnion pikeanum	scientific	Callithamnion pikeanum	ITIS	12937
Anthopleura xanthogrammica	scientific	Anthopleura xanthogrammica	ITIS	52553
foliose bryozoan	scientific	NA	NA	NA
foliose coralline algae	scientific	NA	NA	NA
unidentified sponge	scientific	NA	NA	NA
Petalonia fascia	scientific	Petalonia fascia	ITIS	11432
Microcladia borealis	scientific	Microcladia borealis	ITIS	13081
Dumontia alaskana	scientific	Dumontia alaskana	GBIF Backbone Taxonomy	5279347
Ahnfeltia fastigiata	scientific	Ahnfeltia fastigiata	ITIS	12047
Ulothrix flacca	scientific	Ulothrix flacca	ITIS	6418
Saccharina sessilis	scientific	NA	NA	NA
unidentified worm	scientific	NA	NA	NA
Not Listed	scientific	NA	NA	NA
Hiatella arctica	scientific	Hiatella arctica	ITIS	81765
Constantinea subulifera	scientific	Constantinea subulifera	ITIS	12708
Ectocarpus sp.	scientific	Ectocarpus	ITIS	10696
Pododesmus macroschisma	scientific	Pododesmus macroschisma	ITIS	655987
unidentified filamentous red algae	scientific	NA	NA	NA

**Comment by clnsmth** [comment]
Thanks for this helpful info @timshep.  

Further investigation reveals some areas of the taxonomyCleanr code that could be improved. I'll work on this and provide an update for you to test ~ next week.

**Comment by clnsmth** [comment]
Hey @timshep. I've implemented a fix in the "fix_eal_issue_89" branch of the taxonomyCleanr package. Please test drive this when you get a chance and let me know if it works for you. Install with:

`remotes::install_github("EDIorg/taxonomyCleanr", ref = "fix_eal_issue_89")`

**Comment by timshep** [comment]
Sounds wonderful! I'll try to give it a run soon. Hopefully early next week.

​~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tim Shepherd
Data Manager
Southwest Alaska Network
Inventory and Monitoring Program
National Park Service

Anchorage, AK
________________________________
From: Colin Smith ***@***.***>
Sent: Friday, September 24, 2021 15:06
To: EDIorg/EMLassemblyline ***@***.***>
Cc: Shepherd, Timothy H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDIorg/EMLassemblyline] Taxonomic coverage not returning authority as expected (#89)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hey @timshep<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimshep&data=04%7C01%7Ctim_shepherd%40nps.gov%7Ccffce1541d4e48d52d4d08d97faff667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637681216024797017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G6xnetCY7TaXL6cOic1WfhHFm8%2FdNcBQKRgC65uWVGc%3D&reserved=0>. I've implemented a fix in the "fix_eal_issue_89" branch of the taxonomyCleanr package. Please test drive this when you get a chance and let me know if it works for you. Install with:

remotes::install_github("EDIorg/taxonomyCleanr", ref = "fix_eal_issue_89")

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEDIorg%2FEMLassemblyline%2Fissues%2F89%23issuecomment-926962401&data=04%7C01%7Ctim_shepherd%40nps.gov%7Ccffce1541d4e48d52d4d08d97faff667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637681216024806973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jICghNto02zMBf5AvH8SFHos6jWvtKC%2F%2BNI996P9lvI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAED7D3DAEDXE7MPIKDRGDJDUDT76XANCNFSM5EATA5CQ&data=04%7C01%7Ctim_shepherd%40nps.gov%7Ccffce1541d4e48d52d4d08d97faff667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637681216024806973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LKSjoQbcboJE5dKgitnes6Q%2FKaMbZhku638Vd%2B1bBMM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctim_shepherd%40nps.gov%7Ccffce1541d4e48d52d4d08d97faff667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637681216024816931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HzNkQBgl14Go%2B8HbQWfJBreSBZkFQuDY2qfP5l0PI04%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctim_shepherd%40nps.gov%7Ccffce1541d4e48d52d4d08d97faff667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637681216024816931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qWa5os4WPazFNFTRqcotgIApjVzKSrjOIVdF9Du36vc%3D&reserved=0>.

**Comment by timshep** [comment]
The update did the trick. I've included the coverage file.

If I change the order of the search criteria to WORMS first, WORMS was the most prevalent authority returned.

Tim

​~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tim Shepherd
Data Manager
Southwest Alaska Network
Inventory and Monitoring Program
National Park Service

Anchorage, AK
________________________________

**Comment by clnsmth** [comment]
Thanks @timshep. I've merged this with the development branch and will merge with master after additional testing. I'll post a message here when the master merge is complete.

**Comment by clnsmth** [comment]
FYI @timshep, taxonomyCleanr 1.5.3 has been merged with master and this dependency listed for EAL 3.4.0.
