### ISSUE TITLE
Handle special character (accented letters, apostrophes) in all metadata templates

### ISSUE THREAD

**Issue by kzollove** [EDIorg/EMLassemblyline#90]
These are handled in the .docx templates, but not in personnel or attribute_* templates.

Some of these could be implemented: https://www.princexml.com/doc/characters/

**Comment by clnsmth** [comment]
Thanks for the suggestion @kzollove. Please ensure your inputs are UTF-8 encoded. If the issue persists, then we can look at potential solutions.

**Comment by kzollove** [comment]
Thanks Colin you're right, this does seem to be a problem with encoding. Not sure how to handle it but definitely outside the scope of EAL.

**Comment by clnsmth** [comment]
Thanks for testing this out @kzollove. Just to be clear, EAL did successfully translate the accented characters from an input file when the input was correctly encoded in UTF-8?
