### ISSUE TITLE
Issue a warning/error for semi-colon as part of argument in data.table.name

### ISSUE THREAD

**Issue by kzollove** [EDIorg/EMLassemblyline#93]
The use of semi-colons in the data table name causes an error in the PASTA+ evaluation (attached).

For instance, "Table 1; Site descriptions" causes an error while "Table 1: Site descriptions"

<img width="1656" alt="Screen Shot 2021-10-20 at 11 21 40 AM" src="https://user-images.githubusercontent.com/18039765/138122357-23e64f25-5e8a-4b07-982a-f8cf88200732.png">
on

**Comment by clnsmth** [comment]
@kzollove We're you able to confirm this is a PASTA+ issue?

**Comment by kzollove** [comment]
Yes it is PASTA+ issue. I'll close it out here
